import type { RegisterField } from "@/components/register-page";

export const STATUS_STYLES_GENERIC: Record<string, string> = {
  draft: "bg-zinc-100 text-zinc-700",
  submitted: "bg-blue-100 text-blue-700",
  pending: "bg-amber-100 text-amber-700",
  open: "bg-amber-100 text-amber-700",
  under_review: "bg-amber-100 text-amber-700",
  approved: "bg-emerald-100 text-emerald-700",
  in_progress: "bg-blue-100 text-blue-700",
  ordered: "bg-blue-100 text-blue-700",
  delivered: "bg-emerald-100 text-emerald-700",
  received: "bg-emerald-100 text-emerald-700",
  closed: "bg-zinc-200 text-zinc-600",
  resolved: "bg-emerald-100 text-emerald-700",
  done: "bg-emerald-100 text-emerald-700",
  rejected: "bg-rose-100 text-rose-700",
  paid: "bg-emerald-100 text-emerald-700",
  high: "bg-rose-100 text-rose-700",
  medium: "bg-amber-100 text-amber-700",
  low: "bg-zinc-100 text-zinc-700",
  available: "bg-emerald-100 text-emerald-700",
  in_use: "bg-blue-100 text-blue-700",
  maintenance: "bg-amber-100 text-amber-700",
  present: "bg-emerald-100 text-emerald-700",
  absent: "bg-rose-100 text-rose-700",
};

const opt = (vs: string[]) => vs.map((v) => ({ value: v, label: v.replace(/_/g, " ") }));

export const REGISTERS: Record<string, { title: string; description: string; projectScoped: boolean; statusField?: string; fields: RegisterField[] }> = {
  suppliers: {
    title: "Suppliers", description: "Vendor and subcontractor directory.", projectScoped: false,
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "category", label: "Category" },
      { name: "contact_person", label: "Contact" },
      { name: "phone", label: "Phone" },
      { name: "email", label: "Email" },
      { name: "rating", label: "Rating (0-5)", type: "number", hideInTable: true },
      { name: "address", label: "Address", type: "textarea", hideInTable: true },
      { name: "notes", label: "Notes", type: "textarea", hideInTable: true },
    ],
  },
  cost_codes: {
    title: "Cost Codes", description: "WBS cost code structure used in BOQ and budgets.", projectScoped: false,
    fields: [
      { name: "code", label: "Code", required: true },
      { name: "name", label: "Name", required: true },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
    ],
  },
  procurement_requests: {
    title: "Material Requests", description: "Site material requisitions and approvals.", projectScoped: true, statusField: "status",
    fields: [
      { name: "request_number", label: "Number", required: true },
      { name: "material_name", label: "Material", required: true },
      { name: "quantity", label: "Qty", type: "number" },
      { name: "unit", label: "Unit" },
      { name: "required_date", label: "Required", type: "date" },
      { name: "priority", label: "Priority", type: "select", options: opt(["low", "normal", "high", "urgent"]) },
      { name: "status", label: "Status", type: "select", options: opt(["draft", "submitted", "approved", "ordered", "delivered", "closed", "rejected"]) },
      { name: "reason", label: "Reason", type: "textarea", hideInTable: true },
    ],
  },
  rfqs: {
    title: "RFQs", description: "Requests for quotation sent to suppliers.", projectScoped: true, statusField: "status",
    fields: [
      { name: "rfq_number", label: "Number", required: true },
      { name: "due_date", label: "Due", type: "date" },
      { name: "status", label: "Status", type: "select", options: opt(["draft", "sent", "received", "closed"]) },
      { name: "notes", label: "Notes", type: "textarea", hideInTable: true },
    ],
  },
  purchase_orders: {
    title: "Purchase Orders", description: "Approved purchase orders.", projectScoped: true, statusField: "status",
    fields: [
      { name: "po_number", label: "PO #", required: true },
      { name: "total_amount", label: "Amount", type: "number" },
      { name: "currency", label: "Ccy" },
      { name: "delivery_date", label: "Delivery", type: "date" },
      { name: "status", label: "Status", type: "select", options: opt(["draft", "submitted", "approved", "ordered", "delivered", "closed"]) },
      { name: "notes", label: "Notes", type: "textarea", hideInTable: true },
    ],
  },
  deliveries: {
    title: "Deliveries", description: "Material deliveries to site.", projectScoped: true, statusField: "status",
    fields: [
      { name: "delivery_date", label: "Date", type: "date", required: true },
      { name: "delivered_quantity", label: "Qty", type: "number" },
      { name: "delivery_note", label: "DN #" },
      { name: "status", label: "Status", type: "select", options: opt(["received", "partial", "rejected"]) },
      { name: "notes", label: "Notes", type: "textarea", hideInTable: true },
    ],
  },
  variations: {
    title: "Variations", description: "Variation orders and change requests.", projectScoped: true, statusField: "status",
    fields: [
      { name: "variation_number", label: "VO #", required: true },
      { name: "title", label: "Title", required: true },
      { name: "cost_impact", label: "Cost Impact", type: "number" },
      { name: "time_impact_days", label: "Days", type: "number" },
      { name: "status", label: "Status", type: "select", options: opt(["draft", "submitted", "under_review", "approved", "rejected"]) },
      { name: "reason", label: "Reason", type: "textarea", hideInTable: true },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
    ],
  },
  payment_claims: {
    title: "Payment Claims (IPC)", description: "Interim payment certificates.", projectScoped: true, statusField: "status",
    fields: [
      { name: "claim_number", label: "Claim #", required: true },
      { name: "period_start", label: "From", type: "date" },
      { name: "period_end", label: "To", type: "date" },
      { name: "gross_claim", label: "Gross", type: "number" },
      { name: "net_claim", label: "Net", type: "number" },
      { name: "status", label: "Status", type: "select", options: opt(["draft", "submitted", "under_review", "approved", "paid", "rejected"]) },
      { name: "work_done_value", label: "Work Done", type: "number", hideInTable: true },
      { name: "variation_value", label: "Variations", type: "number", hideInTable: true },
      { name: "material_at_site_value", label: "Material@Site", type: "number", hideInTable: true },
      { name: "retention", label: "Retention", type: "number", hideInTable: true },
      { name: "advance_recovery", label: "Adv Recovery", type: "number", hideInTable: true },
      { name: "deductions", label: "Deductions", type: "number", hideInTable: true },
      { name: "notes", label: "Notes", type: "textarea", hideInTable: true },
    ],
  },
  quality_inspections: {
    title: "Quality Inspections", description: "Quality inspection register.", projectScoped: true, statusField: "status",
    fields: [
      { name: "inspection_number", label: "Insp #", required: true },
      { name: "type", label: "Type" },
      { name: "location", label: "Location" },
      { name: "inspection_date", label: "Date", type: "date" },
      { name: "result", label: "Result", type: "select", options: opt(["pass", "fail", "conditional"]) },
      { name: "status", label: "Status", type: "select", options: opt(["pending", "in_progress", "closed"]) },
      { name: "comments", label: "Comments", type: "textarea", hideInTable: true },
      { name: "photos", label: "Photos", type: "photos", hideInTable: true },
    ],
  },
  safety_inspections: {
    title: "Safety Inspections", description: "Safety walks and audits.", projectScoped: true, statusField: "status",
    fields: [
      { name: "inspection_number", label: "Insp #", required: true },
      { name: "location", label: "Location" },
      { name: "ppe_compliance", label: "PPE" },
      { name: "due_date", label: "Due", type: "date" },
      { name: "status", label: "Status", type: "select", options: opt(["open", "in_progress", "closed"]) },
      { name: "unsafe_acts", label: "Unsafe Acts", type: "textarea", hideInTable: true },
      { name: "unsafe_conditions", label: "Unsafe Conditions", type: "textarea", hideInTable: true },
      { name: "corrective_action", label: "Corrective Action", type: "textarea", hideInTable: true },
      { name: "photos", label: "Photos", type: "photos", hideInTable: true },
    ],
  },
  ncrs: {
    title: "Non-Conformance (NCR)", description: "NCR register.", projectScoped: true, statusField: "status",
    fields: [
      { name: "ncr_number", label: "NCR #", required: true },
      { name: "description", label: "Description", required: true },
      { name: "location", label: "Location" },
      { name: "due_date", label: "Due", type: "date" },
      { name: "status", label: "Status", type: "select", options: opt(["open", "in_progress", "closed"]) },
      { name: "corrective_action", label: "Corrective Action", type: "textarea", hideInTable: true },
      { name: "photos", label: "Photos", type: "photos", hideInTable: true },
    ],
  },
  snags: {
    title: "Snag List", description: "Defects and punch-list items.", projectScoped: true, statusField: "status",
    fields: [
      { name: "snag_number", label: "Snag #", required: true },
      { name: "location", label: "Location" },
      { name: "description", label: "Description", required: true },
      { name: "due_date", label: "Due", type: "date" },
      { name: "status", label: "Status", type: "select", options: opt(["open", "in_progress", "resolved", "closed"]) },
      { name: "photos", label: "Photos", type: "photos", hideInTable: true },
    ],
  },
  risks: {
    title: "Risk Register", description: "Project risk register with probability × impact scoring.", projectScoped: true, statusField: "status",
    fields: [
      { name: "title", label: "Risk", required: true },
      { name: "category", label: "Category" },
      { name: "probability", label: "Prob (1-5)", type: "number" },
      { name: "impact", label: "Impact (1-5)", type: "number" },
      { name: "status", label: "Status", type: "select", options: opt(["open", "mitigated", "closed", "accepted"]) },
      { name: "due_date", label: "Due", type: "date" },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
      { name: "mitigation_action", label: "Mitigation", type: "textarea", hideInTable: true },
    ],
  },
  issues: {
    title: "Issue Register", description: "Project issues and resolutions.", projectScoped: true, statusField: "status",
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "priority", label: "Priority", type: "select", options: opt(["low", "normal", "high", "urgent"]) },
      { name: "due_date", label: "Due", type: "date" },
      { name: "status", label: "Status", type: "select", options: opt(["open", "in_progress", "resolved", "closed"]) },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
      { name: "resolution", label: "Resolution", type: "textarea", hideInTable: true },
    ],
  },
  meetings: {
    title: "Meeting Minutes", description: "Meeting records with attendees and decisions.", projectScoped: true,
    fields: [
      { name: "title", label: "Title", required: true },
      { name: "meeting_date", label: "Date", type: "date", required: true },
      { name: "agenda", label: "Agenda", type: "textarea", hideInTable: true },
      { name: "discussion_points", label: "Discussion", type: "textarea", hideInTable: true },
      { name: "decisions", label: "Decisions", type: "textarea", hideInTable: true },
    ],
  },
  resources: {
    title: "Manpower", description: "Site manpower and attendance.", projectScoped: true, statusField: "attendance_status",
    fields: [
      { name: "employee_name", label: "Name", required: true },
      { name: "trade", label: "Trade" },
      { name: "assigned_date", label: "Date", type: "date" },
      { name: "attendance_status", label: "Attendance", type: "select", options: opt(["present", "absent", "leave"]) },
      { name: "overtime_hours", label: "OT Hrs", type: "number" },
      { name: "remarks", label: "Remarks", type: "textarea", hideInTable: true },
    ],
  },
  equipment: {
    title: "Equipment", description: "Plant and equipment register.", projectScoped: true, statusField: "status",
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "code", label: "Code" },
      { name: "operator", label: "Operator" },
      { name: "status", label: "Status", type: "select", options: opt(["available", "in_use", "maintenance", "broken"]) },
      { name: "usage_hours", label: "Hrs", type: "number" },
      { name: "maintenance_due_date", label: "Maintenance Due", type: "date" },
      { name: "notes", label: "Notes", type: "textarea", hideInTable: true },
    ],
  },
  timesheets: {
    title: "Timesheets", description: "Hours by user per project.", projectScoped: true,
    fields: [
      { name: "work_date", label: "Date", type: "date", required: true },
      { name: "hours", label: "Hours", type: "number", required: true },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
    ],
  },
  milestones: {
    title: "Milestones", description: "Project milestones and dates.", projectScoped: true,
    statusField: "status",
    fields: [
      { name: "name", label: "Name", required: true },
      { name: "description", label: "Description", type: "textarea", hideInTable: true },
      { name: "due_date", label: "Planned", type: "date" },
      { name: "completed_at", label: "Completed", type: "date" },
      { name: "status", label: "Status", type: "select", options: ["not_started","in_progress","completed","delayed","on_hold"] },
      { name: "progress", label: "Progress %", type: "number" },
    ],
  },
};
